[package]
name = "proyecto_primi_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.19.1", features = ["wgpu", "train"] }
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }